### ISSUE TITLE
Error: Attempt to index field 'output_types'

### ISSUE THREAD

**Issue by Shatur** [pianocomposer321/yabs.nvim#10]
The following configuration:

```lua
require('yabs'):setup({
  tasks = {
    build = {
      command = 'echo 1',
      output = 'quickfix',
    },
    run = {
      command = 'echo 2',
      output = 'quickfix',
    },
  },
})
```

Causes `E5108: Error executing lua ...ns/start/yabs.nvim/lua/yabs/defaults/output/quickfix.lua:21: attempt to index field 'output_types' (a nil value)`

**Comment by pianocomposer321** [comment]
Will look into this when I get a chance.
