### ISSUE TITLE
Vimscript API

### ISSUE THREAD

**Issue by lervag** [pianocomposer321/yabs.nvim#15]
As discussed [here](https://www.reddit.com/r/neovim/comments/q60kvp/comment/hg9b11z/?utm_source=reddit&utm_medium=web2x&context=3), I believe it would be convenient for several of us more "old school" neovim users to have a vimscript based API. Something like:

```vim
Plug 'pianocomposer321/yabs.nvim'

" Perhaps something like this
" (Or config through json file?)
let g:yabs_config = {
      \ 'languages': {
      \   'rust': ...
      \ }
      \}

nmap ... <plug>(yabs-run-default-task)
nnoremap ... :call yabs#run_task('build')<cr>
nnoremap ... :call yabs#run_command(...)<cr>
```

**Comment by pianocomposer321** [comment]
I’ll probably add vim commands for running commands on the fly, and maybe plug mappings too. But I fail to see the advantage of the other suggestions.

> ```vim
>" Perhaps something like this
>" (Or config through json file?)
>let g:yabs_config = {
>      \ 'languages': {
>      \   'rust': ...
>      \ }
>      \}

Configuration with global commands for lua plugins is not recommended. I have considered using json for config, and may add it at some point, but atp it’s low priority.

> ```vim
> nnoremap ... :call yabs#run_task('build')<cr>
> nnoremap ... :call yabs#run_command(...)<cr>

I fail to see how this is any better than `nnoremap … :lua require(“yabs”):run_task(“build”)<CR>`?

**Comment by pianocomposer321** [comment]
So I have this basically implemented using the following:

```vim
command! -nargs=1 YabsTask
        \ lua require("yabs"):run_task(<q-args>)

command! YabsDefaultTask
        \ lua require("yabs"):run_default_task()
```

I think that `YabsRun` could be implemented in basically the same way (just `:s/:run_task/.run_command/`), but the only issue is how to handle the `opts` table. I'm not a vimscript expert (which is one of the many reasons I wrote this in lua and not vimscript in the first place :wink:), and I'm not sure what the most elegant way to handle this is.

If you have any ideas, let me know.

**Comment by lervag** [comment]
Great. Completion is not a must have, only nice to have. So this looks good to me.
