### ISSUE TITLE
FZF integration

### ISSUE THREAD

**Issue by lervag** [pianocomposer321/yabs.nvim#16]
Telescope integration is cool, but some of us still linger in "the old ways". Perhaps you could make an fzf integration as well?

**Comment by lervag** [comment]
No problem. FZF is easy enough to work with. Something like this should suffice:

```vim
command! -bang YabsRun call fzf#run(fzf#wrap(
            \ 'yabs',
            \ { 'source': <yabs source>,
            \   'sink': <yabs sink>}, <bang>0))
```

Here `<yabs source>` should be a list of the possible tasks. Do you already have an API function available to get this list?

`<yabs sink>` should be easy enough; we only pass the selected target too `run_task`.

**Comment by pianocomposer321** [comment]
Yes, it’s `yabs:get_tasks()`. By default, this will return all of the tasks, global and local. If you want just global ones or just local ones, you can specify by passing an argument (either `require(“yabs.task”).scopes.GLOBAL` or `require(“yabs.task”).scopes.LOCAL`).

If I’m not mistaken, you can call lua functions from vim script with a variable, I think it’s like `v:lua` or something like that. So you could use that to call the api function. Or you could wrap the function into a vim script function in the same file. It’s up to you really, I’m just throwing out ideas.

**Comment by pianocomposer321** [comment]
Yeah, unfortunately I can't find docs on how to create a fzf extension after a cursory search, and I don't currently have the plugin installed, so I don't think I'll be adding this any time soon. I may do it at some point in the future, but It's definitely not a priority. If you send in a PR though, I'll definitely accept it!
