### ISSUE TITLE
output to `vim.diagnostic` module

### ISSUE THREAD

**Issue by IndianBoy42** [pianocomposer321/yabs.nvim#19]
As you may know, the `vim.lsp.diagnostic` module was recently moved to `vim.diagnostic` so that other sources can use the same interface, and you can interact with them the way you did for `vim.lsp.diagnostic`. 

I think this plugin could output to `vim.diagnostic` then we would get things like virtual text and `vim.diagnostic.goto_next` etc

**Comment by Gelio** [comment]
I've been thinking of using this plugin (or the building blocks, e.g. the code in the `outputs` directory) for running ESLint or the TypeScript compiler and then jumping to the found diagnostics. I arrived at a solution that combines the `quickfix` output and the `errorformat` vim setting to allow jumping through diagnostics.

That said, I am not sure how this plugin would fit into populating `vim.diagnostic`s. It would have to parse the output of the command run, which is similar to what already happens with the quickfix list and `errorformat`. The plugin would also be responsible for clearing stale diagnostics, which also seems challenging.

@IndianBoy42 do you have a concrete idea how you'd expect this plugin to work with `vim.diagnostic`?

**Comment by IndianBoy42** [comment]
That's true it may have to parse the diagnostics, usually regex based parsers are fine, we can look at how null-ls structures it. Probably when the user adds some command they would also specify how to parse the output. Then just shuffle all that data into vim.diagnostic so we get JP to next diag and virtual text and all the plugins that work with vim.diagnostic for free.

Now that I've mentioned null-ls i almost wonder if it would be easier to make null-ls able to run build programs rather than making yabs output to vim.diagnostic

**Comment by Gelio** [comment]
I see. Relying on null-ls to run programs instead seems sensible and would probably result in less work than adding output parsing + outputting diagnostics into yabs.

The downside of using null-ls, though, would be that it runs the program on each file modification if I'm not mistaken. We could rely on [`runtime_condition`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#runtime_condition) to enable it only for a brief moment and then keep that source disabled. Another way would be to register a new "oneshot" source only to run the command, and then de-register it after the command is done.

**Comment by pianocomposer321** [comment]
@IndianBoy42 @Gelio I was actually thinking about this recently too, and I don't think outputting to vim.diagnostic is in scope for this plugin. You could probably already do it yourself using the `output` option, and I've been toying with the possibility of adding "extensions" at some point, and that might be a valid use case for an extension, but at this point I'm not planning it for the base plugin.

That said, AFAIK there's nothing stopping you from using null-ls for linting and yabs for running your program...there shouldn't be any conflicts.

**Comment by pianocomposer321** [comment]
Unless either of you have anything to add, I'll close this, because I don't see this feature being added anytime soon.

**Comment by Gelio** [comment]
I don't mind closing this issue

**Comment by IndianBoy42** [comment]
okay sure, I'll try and figure out if I can do it myself with `output` as you said

**Comment by pianocomposer321** [comment]
@IndianBoy42 sounds good. If you do figure it out, be sure to let me know how you ended up getting it to work!
