### ISSUE TITLE
Proposal: Genrate a default .yabs

### ISSUE THREAD

**Issue by glyh** [pianocomposer321/yabs.nvim#41]
Sometimes we want to improve on existing tasks in specific project, it would be handy if there's some kind of mechanics to generate a default one.

**Comment by pianocomposer321** [comment]
I'm not sure I understand...what would be in the default file? A default configuration would be just "return {}", but there's not much advantage in generating that...

**Comment by glyh** [comment]
I mean the default config of all presenting file types should be copied to a new file. This can:
1. make it easier for one to modify the default behaviors.
2. Get persistent behavior across users easier.

**Comment by pianocomposer321** [comment]
Since I've rewritten yabs (see [my blog post](https://pianocomposer321.github.io/2022/05/03/why-im-rewriting-yabs.html)), and this is no longer relevant with the new version (which does not have .yabs files), I'm closing this.
