### ISSUE TITLE
Roadmap/TODO

### ISSUE THREAD

**Issue by pianocomposer321** [pianocomposer321/yabs.nvim#5]
## Things I would like to see added to this plugin.

 - [x] Task list

Instead of having just one command to run with `require(“yabs”):build()`, I would like to have multiple “tasks” available to run, a la vscode or asynctasks.vim. Setup would look something like this:

```lua
require(“yabs”):setup {
    languages = {
        cpp = {
            default_task = “build&run”,
            tasks = {
                build = {
                    command = “g++ main.cpp -std=c++17 -o main”,
                    output = “quickfix”
                },
                run = {
                    command = “./main”
                    output = “terminal”
                }
            }
        }
    }
}
```

To run a task, you would do something like `require(“yabs”):run_task(“build”)`. There may be some special syntax available to run more than one task, similar to the shell `&&`. So to build and run, maybe something like `require(“yabs”):run_task(“build&run”)`. If this feature is implemented, it would likely have some sort of error checking so that if one command fails, subsequent ones are not run anyway.

Probably there would be a way to set global tasks, which would be useful in a `.yabs` file. These would override the language-specific ones in that project.

 - [x] Convert `.yabs` file to `.yabs.json`

Having a file automatically detected and run as a lua script is a potential security risk. Making the config file a json file instead would alleviate that, but could require some luarocks dependencies, which is something I have yet to look into, or require the use of some more obscure vim functions, which may not be very easy to work with from lua.

CC: @Shatur, Ref: https://github.com/pianocomposer321/yabs.nvim/issues/3#issuecomment-917540185

**Comment by Shatur** [comment]
>  Task list

I usually use one task for one file format. 
But sounds useful :)

> similar to the shell &&

It won't be very obvious. How about a variadic number arguments? Like `require("yabs"):run_task("build", "run", "etc")`.
Or a simple array should be fine to.

> Probably there would be a way to set global tasks

Do you mean tasks that are not tied to a specific language? Yes, that would be great! Asynktasks have a similar functionality.

> Convert .yabs file to .yabs.json

I kinda like your approach with lua file... I just so flexible right now :) I would leave it as is.
But I understand your concerns about security.

**Comment by pianocomposer321** [comment]
> It won't be very obvious. How about a variadic number arguments? Like require("yabs"):run_task("build", "run", "etc").
Or a simple array should be fine to.

I like that idea.

> Do you mean tasks that are not tied to a specific language? Yes, that would be great! Asynktasks have a similar functionality.

Exactly. These would mainly be used from the .yabs file. For example, you probably want the “build” task to do the same thing in that project even if you’re not currently editing a .cpp file.

> I kinda like your approach with lua file... I just so flexible right now :) I would leave it as is.
But I understand your concerns about security.

Thanks for the input. Maybe I could make this a config option…have it act as a lua file by default, but if the user is concerned about security, they could set the config option to have it be a json file instead.

In any case, I think that change will be farther down the line, as I have other priorities right now.

**Comment by Shatur** [comment]
> Exactly. These would mainly be used from the .yabs file. For example, you probably want the “build” task to do the same thing in that project even if you’re not currently editing a .cpp file.

It would be nice!
By the way, what do you think about the ability to pick such task from Telescope? This will not make the plugin tied to Telescope, since the extension is only loaded by Telescope itself. Many plugins do it :)

> Thanks for the input. Maybe I could make this a config option…

What would you prefer personally? It is impossible to think over all possible ways of using the plugin :) Sometimes it's better to come with a simpler implementation for maintenance reasons.

**Comment by pianocomposer321** [comment]
> By the way, what do you think about the ability to pick such task from Telescope? This will not make the plugin tied to Telescope, since the extension is only loaded by Telescope itself. Many plugins do it :)

I have thought about it, and it would be nice for the future. At this moment in time I have no idea how to do it, but I’m sure I could figure it out. I saw that you do something similar in your plugin, so I might look there for inspiration as well.

> What would you prefer personally? It is impossible to think over all possible ways of using the plugin :) Sometimes it's better to come with a simpler implementation for maintenance reasons.

True enough :wink:. I think I’ll keep it how it is for now, but if someone specifically asks for it to change later or I think of an elegant way to make it optional, I might do so at some point.

**Comment by Shatur** [comment]
> I have thought about it, and it would be nice for the future.

I could send a PR once you implement the global tasks feature :)

**Comment by pianocomposer321** [comment]
> > I have thought about it, and it would be nice for the future.
> 
> I could send a PR once you implement the global tasks feature :)

That would be greatly appreciated!

**Comment by Shatur** [comment]
So the task list is ready. Do you want me to send a PR for Telescope picker?
I thinking about three pickers -  `tasks` (maybe rename to all tasks?), `current_language_tasks`, `global_tasks`?

**Comment by pianocomposer321** [comment]
That would be great!

Something to think about though:
I think for many of the built in pickers (`files`, `git_files`, etc.), you can provide an argument to narrow the scope of the search (e.g. provide a file path). So maybe instead of making three separate pickers, you could make just one, probably called `tasks`, and just give the ability to pass an optional argument to specify just the current language ones or just the global ones.

**Comment by pianocomposer321** [comment]
Also, what I’ll probably be working on for the next little bit is rewriting the README (again 🙄), probably on a new `docs` branch. If you could provide relevant documentation for the telescope aspect, either in the same PR or a subsequent one, that would be very appreciated as well!

Otherwise, I can probably write it too, it’s just I think it would be better coming from the person writing the PR providing the feature, so that way I don’t get something wrong in the docs because I don’t fully understand the feature myself yet. Having docs provided would be great for me as well, actually, so I fully understand what’s being merged before doing so, if that makes sense.

**Comment by Shatur** [comment]
> I think for many of the built in pickers (files, git_files, etc.), you can provide an argument to narrow the scope of the search (e.g. provide a file path). So maybe instead of making three separate pickers, you could make just one, probably called tasks, and just give the ability to pass an optional argument to specify just the current language ones or just the global ones.

Sure! I meant to provide `:Telescope yabs [tasks/global_tasks/language_tasks]`. Pretty standard approach. A single yabs extension with three different pickers inside as a third argument.

>  If you could provide relevant documentation for the telescope aspect, either in the same PR or a subsequent one, that would be very appreciated as well!

No problem!

**Comment by pianocomposer321** [comment]
> Sure! I meant to provide :Telescope yabs [tasks/global_tasks/language_tasks]. A single yabs extension with three different pickers inside as a third argument. Pretty standard approach, all extensions works this way :)

Sounds good!
Shows what little I know about extending telescope…

**Comment by Shatur** [comment]
Can be closed I assume?

**Comment by pianocomposer321** [comment]
Sure. I’m still not completely settled on what to do about the `.yabs` file, but I’ll probably just create a new tracking issue for that if I ever decide to change it.

**Comment by Shatur** [comment]
Okay!

**Comment by Shatur** [comment]
Probably we should update the README :)

**Comment by pianocomposer321** [comment]
Agreed, working on it.

**Comment by pianocomposer321** [comment]
https://github.com/pianocomposer321/yabs.nvim/commit/36acfab85abb2bbf59d647871bc2a98cf4c2f964
I think it should be good now, but a second pair of eyes would be welcomed to make sure I’m not missing something.

**Comment by Shatur** [comment]
Looks great!

**Comment by p00f** [comment]
I have 3 tasks for cpp: build, run and clean and `default_task` is `{ "build", "run", "clean" }`. However it looks like they run out of order sometimes.

**Comment by p00f** [comment]
config:
```lua
local _2afile_2a = ".config/nvim/fnl/dotfiles/plugins/yabs.fnl"
local _0_
do
	local name_0_ = "dotfiles.plugins.yabs"
	local module_0_
	do
		local x_0_ = package.loaded[name_0_]
		if "table" == type(x_0_) then
			module_0_ = x_0_
		else
			module_0_ = {}
		end
	end
	module_0_["aniseed/module"] = name_0_
	module_0_["aniseed/locals"] = ((module_0_)["aniseed/locals"] or {})
	do
	end
	(module_0_)["aniseed/local-fns"] = ((module_0_)["aniseed/local-fns"] or {})
	do
	end
	(package.loaded)[name_0_] = module_0_
	_0_ = module_0_
end
local autoload
local function _1_(...)
	return (require("aniseed.autoload")).autoload(...)
end
autoload = _1_
local function _2_(...)
	local ok_3f_0_, val_0_ = nil, nil
	local function _2_()
		return { require("yabs") }
	end
	ok_3f_0_, val_0_ = pcall(_2_)
	if ok_3f_0_ then
		_0_["aniseed/local-fns"] = { require = { yabs = "yabs" } }
		return val_0_
	else
		return print(val_0_)
	end
end
local _local_0_ = _2_(...)
local yabs = _local_0_[1]
local _2amodule_2a = _0_
local _2amodule_name_2a = "dotfiles.plugins.yabs"
do
	local _ = ({ nil, _0_, nil, { {}, nil, nil, nil } })[2]
end
return yabs:setup({
	languages = {
		cpp = {
			default_task = { "build", "run", "clean" },
			tasks = {
				build = { command = "g++ foo.cpp -o main", output = "quickfix" },
				clean = { command = "rm main", output = "echo", type = "shell" },
				run = { command = "./main", output = "terminal" },
			},
		},
		java = { command = "java %", output = "buffer" },
		lua = { command = "lua %", output = "buffer" },
		python = { command = "python %", output = "buffer" },
		rust = { command = "RustRun", output = "echo", type = "vim" },
	},
	output_types = { quickfix = { open_on_run = "auto" } },
})
```

**Comment by p00f** [comment]
config:
``lua
local yabs = require("yabs")
return yabs:setup({
    languages = {
        cpp = {
            default_task = { "build", "run", "clean" },
            tasks = {
                build = { command = "g++ foo.cpp -o main", output = "quickfix" },
                clean = { command = "rm main", output = "echo", type = "shell" },
                run = { command = "./main", output = "terminal" },
            },
        },
        java = { command = "java %", output = "buffer" },
        lua = { command = "lua %", output = "buffer" },
        python = { command = "python %", output = "buffer" },
        rust = { command = "RustRun", output = "echo", type = "vim" },
    },
    output_types = { quickfix = { open_on_run = "auto" } },
})
```

**Comment by pianocomposer321** [comment]
> I have 3 tasks for cpp: build, run and clean and `default_task` is `{ "build", "run", "clean" }`. However it looks like they run out of order sometimes. i.e clean then run then build

Yeah, I anticipated this might be an issue. The tasks are actually _starting_ in the order specified, but because they are asynchronous, the next one will often start before the previous one finishes. This is just the nature of being asynchronous. I may be able to come up with a fix for this…for now, the only workaround I could think of to fix this (sort of) immediately is for you to add another task called something like `build_and_run` that just runs the same commands as `build` and `run` in the terminal. Unfortunately, that would mean that you don’t get output to the quickfix…but I think it’s the best solution I can offer you at the moment. If you could make a separate issue to track this, I can see what solutions I can come up with eventually.

**Comment by p00f** [comment]
Ah ok I didn't make a new issue because this was not on master
